title: Xiaotian Sun
logo: xiaotian_sun.png
description: Ph.D. student in Xi'an Jiaotong University. Email: xtsun@stu.xjtu.edu.cn
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme